### ISSUE TITLE
Clipboard and Register buttons not functioning in SSH.

### ISSUE THREAD

**Issue by seulgiism** [Xpl0itU/passiveMachine#1]
Hi,

Could you add the option to copy the register url to the clipboard? Or have it print somewhere else since I am using it through SSH.
EarnsApp and Mysterium can't be used; I don't know what Mysterium is, can't find it through googling besides a VPN where you have to pay for.

EarnsApp needs to be activated by using the url it seems.
Would love to have a solution :)

**Comment by Xpl0itU** [comment]
Mind trying with 1.5 or later?

**Comment by seulgiism** [comment]
> Mind trying with 1.5 or later?

thanks it works ;)
